name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Match the Node.js version used in the project
          cache: 'npm'
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Build Source Code
        run: npm run build
        
      # TODO: add Jest/unit tests
      # - name: Run Tests
      #   run: npm test