name: Security and Code Scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  ci-security:
    uses: ./.github/workflows/reusable-ci.yml
    with:
      run_quality: false
      run_security: true
    secrets: inherit
