on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  quality-check:
    name: Code Quality Scan
    runs-on: ubuntu-latest 
    
    steps: 
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required by SonarQube for an accurate scan

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}